version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis  # Override .env value
      - REDIS_PORT=6379   # Override .env value
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build: .
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis  # Override .env value
      - REDIS_PORT=6379   # Override .env value
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PYTHONUNBUFFERED=1  # Ensure Python output is sent straight to container log
    depends_on:
      - redis
    command: python -m app.worker
    deploy:
      replicas: ${WORKER_REPLICAS:-1}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes  # Enable persistence

volumes:
  redis_data: 